Add gateway
bartoszdabr/RSWW pull request #29
Opened 2023-06-03 12:17 UTC by rborek32

2023-06-03 12:52 UTC, ulxori commented on apps/Gateway/conf/nginx.conf
> +}
Mógłbyś dodać obsługę Corsa, którą podesłał Bartek?

2023-06-03 12:52 UTC, ulxori commented on docker-compose.yml
> +      -
Niepotrzebnie linia

2023-06-03 12:54 UTC, ulxori commented on docker-compose.yml
>  version: '3.4'
dodaj też do docker-composa przeznaczonego do deva

2023-06-04 08:01 UTC, bartoszdabr requested changes

2023-06-04 08:01 UTC, bartoszdabr commented on apps/Gateway/conf/nginx.conf
> +        location /api {
Tego raczej nie powinno być, nie mamy ścieżki /api do żadnego serwisu, a w linku to był tylko przykład. Cors powinien być ustawiony na poziomie każdego z przekierowań lub w ogóle na poziomie serwera o ile się da

2023-06-04 16:03 UTC, bartoszdabr approved these changes

2023-06-04 16:03 UTC, merged